version: '3'
services:
  api:
    image: node:16
    hostname: helpkb_api
    ports:
      - 4000:4000
    volumes:
      - ./api:/usr/local/app
    depends_on:
      - db
    restart: always
    working_dir: /usr/local/app
    entrypoint: "/bin/bash"
    command: "-c \"if [ ! -d \"node_modules\" ]; then npm i; fi; node app.js\""
    environment:
      # Set environment variables: https://github.com/vercel/next.js/discussions/15651
      - NODE_ENV=development
      - DB_HOST=helpkb_db
      - DB_PORT=5432
      - DB_NAME=helpkb-test
      - DB_USERNAME=postgres
      - DB_PASSWORD=helpkb
      - UI_PORT=3000
      - BASE_URL=http://localhost
      - NEXTAUTH_SECRET=random-string
      - GITHUB_CLIENT_ID=github-client-id
      - GITHUB_SECRET=github-secret
      - NEXT_PUBLIC_GITHUB_CLIENTID=github-client-id
  db:
    image: postgres
    hostname: helpkb_db
    command: -p 5432
    ports:
      - 5432
    environment:
      POSTGRES_DB: helpkb-test
      POSTGRES_PASSWORD: helpkb
      POSTGRES_USER: postgres
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile-nginx
    depends_on:
      - db
      - api
      - ui
    ports:
      - 80:80
  ui:
    hostname: helpkb_ui
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app
    command: npm run dev:ui
    depends_on:
      - api
      - db
    ports:
      - 3000:3000
    environment:
      - BUILD_DIR=./.next
      - UI_PORT=3000
      - NODE_ENV=development
      - HOSTNAME=http://localhost
      - BASE_URL=http://localhost
      - NEXT_PUBLIC_BASE_URL=http://localhost